import { NewsItem } from './types';
import nlp from 'compromise';

// ── Load GeoNames data ──────────────────────────────────────────────────────
// Generated by scripts/build-geodata.mjs from cities5000.txt + admin1CodesASCII.txt
import geoData from '../../data/geonames.json';

interface GeoCity { lat: number; lon: number; pop: number; cc: string }
interface GeoRegion { lat: number; lon: number; cc: string }

const geoCities: Record<string, GeoCity> = (geoData as Record<string, unknown>).cities as Record<string, GeoCity>;
const geoAdmin1: Record<string, GeoRegion> = (geoData as Record<string, unknown>).admin1 as Record<string, GeoRegion>;
const geoCountries: Record<string, GeoRegion> = ((geoData as Record<string, unknown>).countries || {}) as Record<string, GeoRegion>;

// cache geocode promises to dedupe concurrent requests for the same place
const geoCache = new Map<string, Promise<{ lat: number; lon: number; displayName: string } | null>>();

// ── Build location dictionary ───────────────────────────────────────────────
// Priority: hardcoded overrides > GeoNames cities (population-weighted) > admin1 regions

interface LocationEntry {
    lat: number;
    lon: number;
    pop: number;          // population (0 for countries/admin1)
    type: 'city' | 'admin1' | 'country' | 'landmark';
}

const KNOWN_LOCATIONS: Record<string, LocationEntry> = {};

// 1. Load GeoNames cities (population-weighted — highest pop wins on name collision)
for (const [key, city] of Object.entries(geoCities)) {
    if (key.length <= 2) continue;
    KNOWN_LOCATIONS[key] = { lat: city.lat, lon: city.lon, pop: city.pop, type: 'city' };
}

// 2. Load admin1 regions (states/provinces) — only if not already occupied by a large city
for (const [key, region] of Object.entries(geoAdmin1)) {
    if (key.length <= 2) continue;
    const existing = KNOWN_LOCATIONS[key];
    // Don't overwrite a city with > 500k pop with an admin1 region
    if (existing && existing.pop > 500000) continue;
    KNOWN_LOCATIONS[key] = { lat: region.lat, lon: region.lon, pop: 0, type: 'admin1' };
}

// 3. Countries from geonames.json — always override with their canonical centroids
// This loads 209+ country names (including Albania, Croatia, Senegal, etc.)
for (const [name, data] of Object.entries(geoCountries)) {
    if (name.length <= 2) continue;
    KNOWN_LOCATIONS[name] = { lat: data.lat, lon: data.lon, pop: 0, type: 'country' };
}

// 4. Hardcoded landmarks & conflict zones — highest priority overrides
const LANDMARKS: Record<string, { lat: number; lon: number }> = {
    'pentagon': { lat: 38.87, lon: -77.06 }, 'white house': { lat: 38.90, lon: -77.04 },
    'kremlin': { lat: 55.75, lon: 37.62 }, 'vatican': { lat: 41.90, lon: 12.45 },
    'gaza city': { lat: 31.50, lon: 34.47 }, 'west bank': { lat: 31.95, lon: 35.23 },
    'crimea': { lat: 44.95, lon: 34.10 }, 'donbas': { lat: 48.00, lon: 37.80 },
    'kharkiv': { lat: 49.99, lon: 36.23 }, 'odesa': { lat: 46.48, lon: 30.73 },
    'mariupol': { lat: 47.10, lon: 37.55 }, 'kherson': { lat: 46.64, lon: 32.62 },
    'aleppo': { lat: 36.20, lon: 37.16 }, 'mosul': { lat: 36.34, lon: 43.12 },
    'rafah': { lat: 31.30, lon: 34.25 }, 'khan younis': { lat: 31.35, lon: 34.30 },
    'kyiv': { lat: 50.45, lon: 30.52 }, 'kiev': { lat: 50.45, lon: 30.52 },
    'washington dc': { lat: 38.91, lon: -77.04 },
    // Capital cities with ambiguous short names (override small-city collisions)
    'sanaa': { lat: 15.35, lon: 44.21 }, "sana'a": { lat: 15.35, lon: 44.21 },
    'sana': { lat: 15.35, lon: 44.21 },  // Overrides Sana, Peru (pop 39k) — Sana'a is almost always the intent in OSINT context
    // Strategic waterways & maritime chokepoints (common in OSINT/conflict news)
    'strait of hormuz': { lat: 26.57, lon: 56.25 },
    'suez canal': { lat: 30.46, lon: 32.35 },
    'bab el-mandeb': { lat: 12.58, lon: 43.33 },
    'taiwan strait': { lat: 24.00, lon: 119.00 },
    'strait of malacca': { lat: 2.50, lon: 101.50 },
    'south china sea': { lat: 12.00, lon: 113.00 },
    'black sea': { lat: 43.00, lon: 35.00 },
    'red sea': { lat: 20.00, lon: 38.50 },
    'golan heights': { lat: 33.00, lon: 35.75 },
};

for (const [name, coords] of Object.entries(LANDMARKS)) {
    KNOWN_LOCATIONS[name] = { lat: coords.lat, lon: coords.lon, pop: 0, type: 'landmark' };
}

// ── Demonym map ─────────────────────────────────────────────────────────────
const DEMONYM_MAP: Record<string, string> = {
    'american': 'united states', 'chinese': 'china', 'russian': 'russia',
    'indian': 'india', 'japanese': 'japan', 'german': 'germany',
    'french': 'france', 'british': 'united kingdom', 'canadian': 'canada',
    'brazilian': 'brazil', 'australian': 'australia', 'mexican': 'mexico',
    'italian': 'italy', 'spanish': 'spain', 'korean': 'south korea',
    'iranian': 'iran', 'iraqi': 'iraq', 'syrian': 'syria',
    'turkish': 'turkey', 'israeli': 'israel', 'palestinian': 'palestine',
    'egyptian': 'egypt', 'saudi': 'saudi arabia', 'pakistani': 'pakistan',
    'afghan': 'afghanistan', 'nigerian': 'nigeria', 'kenyan': 'kenya',
    'ethiopian': 'ethiopia', 'sudanese': 'sudan', 'somali': 'somalia',
    'libyan': 'libya', 'yemeni': 'yemen', 'lebanese': 'lebanon',
    'jordanian': 'jordan', 'polish': 'poland', 'dutch': 'netherlands',
    'belgian': 'belgium', 'swedish': 'sweden', 'norwegian': 'norway',
    'danish': 'denmark', 'finnish': 'finland', 'greek': 'greece',
    'portuguese': 'portugal', 'swiss': 'switzerland', 'austrian': 'austria',
    'romanian': 'romania', 'hungarian': 'hungary', 'czech': 'czech republic',
    'indonesian': 'indonesia', 'filipino': 'philippines', 'vietnamese': 'vietnam',
    'thai': 'thailand', 'taiwanese': 'taiwan', 'malaysian': 'malaysia',
    'singaporean': 'singapore', 'argentinian': 'argentina', 'colombian': 'colombia',
    'chilean': 'chile', 'venezuelan': 'venezuela', 'peruvian': 'peru',
    'cuban': 'cuba', 'irish': 'ireland', 'scottish': 'scotland',
    'welsh': 'wales', 'moroccan': 'morocco', 'tunisian': 'tunisia',
    'algerian': 'algeria', 'ecuadorian': 'ecuador', 'bolivian': 'bolivia',
    'ukrainian': 'ukraine', 'georgian': 'georgia', 'armenian': 'armenia',
};

// ── Country abbreviation map ────────────────────────────────────────────────
// Common abbreviated country references found in news text ("U.S. casualties" → United States)
const COUNTRY_ABBREV_MAP: Record<string, string> = {
    'u.s.': 'united states', 'u.s.a.': 'united states', 'u.s': 'united states',
    'us': 'united states',
    'u.k.': 'united kingdom', 'u.k': 'united kingdom',
    'u.a.e.': 'united arab emirates', 'uae': 'united arab emirates',
    'u.n.': '__skip__',  // Not a country
    'e.u.': '__skip__',  // Not a country
    'd.c.': 'washington dc',
};

// ── Patterns ────────────────────────────────────────────────────────────────

// regex for standard journalistic datelines (e.g. "WASHINGTON (Reuters) - ")
const DATELINE_PATTERN = /^([A-Z][A-Za-z\s]+?)\s*(?:\([^)]+\))?\s*(?:-|—|–|:)\s+/;

// Words that indicate a section/topic label rather than a geographic dateline.
// When a dateline candidate contains any of these, it's treated as a section header
// (e.g. "Iran Live Updates:" is a topic label, not a dateline like "TEHRAN:").
const DATELINE_NOISE_WORDS = new Set([
    'live', 'updates', 'update', 'breaking', 'latest', 'analysis',
    'opinion', 'editorial', 'exclusive', 'recap', 'roundup', 'review',
    'briefing', 'explainer', 'report', 'summary', 'watch', 'alert',
    'blog', 'tracker', 'results', 'polls', 'podcast', 'newsletter',
    // Military commands that can appear as dateline-like prefix (\"CENTCOM: ...\")
    'centcom', 'eucom', 'africom', 'indopacom', 'southcom', 'northcom',
]);

// "City, State" or "City, Country" comma-pair pattern
const COMMA_PAIR_PATTERN = /([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)*),\s*([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)*)/g;

// regex patterns to pull "in Place", "from Place", "bombards Place", etc.
// Verbs use explicit [Aa] style casing so headline capitals match without /i flag,
// which would break the [A-Z] location-capture group.
const LOCATION_PATTERNS = [
    // Prepositions
    /\bin\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\bin\s+the\s+([A-Z][a-zA-Z]+(?:\s+(?:of\s+)?[A-Z][a-zA-Z]+){0,3})/g,  // "in the Strait of Hormuz"
    /\bfrom\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\bnear\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\bacross\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\boff\s+(?:the\s+coast\s+of\s+)?([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\bto\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\bat\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\btowards?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b(?:city|town|province|state|region|village)\s+of\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    // Present-tense action verbs
    /\b[Hh]its?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ss]trikes?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Aa]ttacks?\s+(?:[Oo]n\s+)?([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ff]ighting\s+in\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ww]ar\s+in\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Cc]risis\s+in\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ii]nvades?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Oo]ccupied\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Bb]ombards?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ss]hells?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Tt]argets?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ss]eizes?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Cc]aptures?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Rr]aids?\s+(?:[Oo]n\s+)?([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Bb]esieges?\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ff]lees?\s+to\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Dd]eploys?\s+to\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    // Past-tense variants
    /\b[Aa]ttacked\s+in\s+(?:the\s+)?([A-Z][a-zA-Z]+(?:\s+(?:of\s+)?[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Tt]argeted\s+(?:in\s+)?(?:the\s+)?([A-Z][a-zA-Z]+(?:\s+(?:of\s+)?[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Ss]helled\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
    /\b[Bb]ombed\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/g,
];

// words regex might catch but aren't locations
const STOP_WORDS = new Set([
    // months & days
    'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august',
    'september', 'october', 'november', 'december', 'monday', 'tuesday',
    'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
    // seasons
    'spring', 'summer', 'fall', 'winter',
    // determiners & pronouns
    'the', 'this', 'that', 'these', 'those', 'what', 'which', 'who', 'how',
    'just', 'new', 'more', 'most', 'some', 'many', 'much', 'its', 'his', 'her',
    'their', 'our', 'all', 'one', 'two', 'three', 'four', 'five',
    // news & media terms
    'congress', 'senate', 'parliament', 'reuters', 'associated',
    'press', 'exclusive', 'breaking', 'update', 'live', 'latest',
    'report', 'reports', 'analysis', 'opinion', 'editorial',
    // common false-positive capitalized words
    'trump', 'biden', 'putin', 'modi', 'macron', 'scholz', 'zelenskyy',
    'zelensky', 'netanyahu', 'xi', 'obama', 'pope', 'elon', 'musk',
    'democrats', 'republicans', 'nato', 'opec', 'who', 'fbi', 'cia',
    'deal', 'record', 'back', 'first', 'second', 'third', 'over',
    'after', 'before', 'major', 'global', 'world', 'international',
    'north', 'south', 'east', 'west', 'says', 'say', 'said',
    'each', 'every', 'both', 'other', 'another', 'such',
    'high', 'higher', 'low', 'lower', 'big', 'small', 'long',
    'war', 'peace', 'crisis', 'today', 'yesterday', 'tomorrow',
    'government', 'president', 'minister', 'prime', 'general',
    'military', 'army', 'force', 'forces', 'troops', 'police',
    'court', 'supreme', 'justice', 'law', 'bill', 'act',
    'company', 'companies', 'stocks', 'market', 'markets',
    'people', 'officials', 'sources', 'leaders', 'workers',
    // space agencies & organizations (false positives from "from NASA", etc.)
    'nasa', 'esa', 'spacex', 'jaxa', 'isro', 'roscosmos',
    'un', 'united nations', 'imf', 'interpol',
    // military commands & coalitions (organizational names, not locations)
    'centcom', 'eucom', 'africom', 'indopacom', 'southcom', 'northcom',
    'socom', 'transcom', 'stratcom', 'cybercom', 'spacecom',
    // celestial bodies (NLP/regex catches "Venus", "Mars", etc.)
    'moon', 'sun', 'venus', 'mars', 'jupiter', 'saturn', 'mercury',
    'neptune', 'uranus', 'pluto', 'earth', 'lunar', 'solar',
    'asteroid', 'comet', 'nebula', 'galaxy', 'orbit', 'spacecraft',
    // generic geographic words that aren't specific locations
    'island', 'islands', 'peninsula', 'continent', 'region', 'area',
    'coast', 'mountain', 'river', 'lake', 'ocean', 'sea', 'bay', 'gulf',
    // continent names — too broad for map pins, and some collide with small cities
    // (e.g. "Asia" → small town in Indonesia, "Europe" → unincorporated community in US)
    'asia', 'europe', 'africa', 'antarctica', 'oceania', 'americas',
    // structured metadata labels (ReliefWeb: "Country: Yemen Source: WFP")
    'country', 'source', 'category', 'theme', 'format', 'topic',
    // timezone abbreviations that get caught by comma-pair ("ET, March")
    'et', 'pt', 'ct', 'mt', 'est', 'pst', 'cst', 'mst', 'gmt', 'utc',
]);

// ── False positives ─────────────────────────────────────────────────────────
// Names, brands, and sports teams that NLP/regex detect as geographic places.
// These get checked against BOTH the raw candidate AND the disambiguated key.
const FALSE_POSITIVES = new Set([
    // Multi-word names where the first word is also a real place
    'paris hilton', 'jackson hole', 'georgia tech',
    'chelsea clinton', 'chelsea handler', 'virginia woolf',
    // Sports teams (these match city names but are rarely used as location references)
    'arsenal', 'chelsea fc', 'manchester united', 'manchester city',
    'real madrid', 'bayern munich', 'juventus', 'napoli',
    'tottenham', 'everton', 'wolverhampton', 'newcastle united',
    // Brands / companies that are also place names
    'amazon', 'apple', 'oracle', 'adobe', 'cisco',
    // Social media source names & handles that regex/NLP might pick up
    'liveuamap', 'middleeast', 'middle east', 'nitter', 'osint',
    'geoconfirmed', 'intelcrab', 'auroraintel', 'osinttechnical',
    // Common compound false positives from news headlines
    'research roundup', 'audio long read', 'author correction',
    'weekend of war', 'morning edition', 'evening update',
    'daily briefing', 'weekly roundup', 'year in review',
]);

// ── News source default locations ───────────────────────────────────────────
// Fallback locations for well-known news providers whose articles often lack
// extractable geographic context (e.g. "NASA discovers new exoplanet").
// These are used as a LAST resort when no location can be found at all.
const NEWS_SOURCE_DEFAULTS: Record<string, string> = {
    'nasa': 'Washington DC',
    'nature': 'London',
    'ars technica': 'San Francisco',
    'the verge': 'New York',
    'who': 'Geneva',
};

// ── Helper functions ────────────────────────────────────────────────────────

// Clean a candidate: strip possessives, trailing punctuation, etc.
function cleanCandidate(raw: string): string {
    let s = raw.trim();
    s = s.replace(/['\u2019]s\b/g, '');      // "Canada's" → "Canada"
    s = s.replace(/[.,;:!?"')]+$/, '');       // trailing punctuation
    s = s.replace(/^["'(]+/, '');             // leading punctuation
    return s.trim();
}

// Safe disambiguate: check exact match ONLY. No destructive word-chopping.
// If the full phrase is in the dictionary, return it. Otherwise return as-is.
function disambiguate(candidate: string): string {
    const key = candidate.toLowerCase().trim();
    if (KNOWN_LOCATIONS[key]) return candidate;
    // Do NOT chop words — let the API handle unknown multi-word names
    return candidate;
}

// Try to resolve a demonym ("Chinese" → "China")
function extractDemonym(text: string): string | null {
    const words = text.split(/\s+/);
    for (const word of words) {
        const lower = word.toLowerCase().replace(/[^a-z]/g, '');
        if (DEMONYM_MAP[lower]) {
            return DEMONYM_MAP[lower];
        }
    }
    return null;
}

// Try to resolve country abbreviations in text ("U.S." → "united states")
// Keeps periods so we can match "U.S." properly, unlike demonyms which strip punctuation
function extractCountryAbbrev(text: string): string | null {
    // Split on whitespace but preserve punctuation (periods) within tokens
    const tokens = text.split(/\s+/);
    for (const token of tokens) {
        // Normalize: lowercase, strip trailing commas/colons/semicolons but keep periods
        const cleaned = token.toLowerCase().replace(/[,;:!?'")\]]+$/, '').replace(/^['"(\[]+/, '');
        const mapped = COUNTRY_ABBREV_MAP[cleaned];
        if (mapped && mapped !== '__skip__') {
            return mapped;
        }
    }
    return null;
}

// Determine the priority type of a location (lower = more specific = better)
// For country/city name collisions (e.g. "Albania" the country vs "Albania" the city
// in Colombia), the country wins unless the city has >1M population.
function locationPriority(key: string): number {
    const entry = KNOWN_LOCATIONS[key];
    if (!entry) return 99;
    switch (entry.type) {
        case 'landmark': return 0;
        case 'city': return entry.pop > 1000000 ? 1 : 1.5;  // Only mega-cities beat countries
        case 'admin1': return 2;
        case 'country': return 1.2;  // Countries beat small/medium cities
        default: return 4;
    }
}

// ── Main extraction ─────────────────────────────────────────────────────────

interface Candidate {
    name: string;
    source: 'dateline' | 'comma_pair' | 'regex' | 'nlp' | 'demonym';
}

export function extractLocation(title: string, description: string): string | null {
    const candidates: Candidate[] = [];

    // Helper: check if a dateline candidate is a genuine geographic dateline
    // vs a section label like "Iran Live Updates:" or "Breaking News:"
    function isGenuineDateline(raw: string): boolean {
        const words = raw.toLowerCase().split(/\s+/);
        return !words.some(w => DATELINE_NOISE_WORDS.has(w));
    }

    // 1a. Structured metadata pattern (ReliefWeb, humanitarian feeds)
    // Matches: "Country: Yemen Source: WFP" → extracts "Yemen" as dateline-priority
    const METADATA_COUNTRY = /\bCountry:\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/;
    const metaMatch = METADATA_COUNTRY.exec(description) || METADATA_COUNTRY.exec(title);
    if (metaMatch) {
        candidates.push({ name: metaMatch[1].trim(), source: 'dateline' });
    }

    // 1b. Dateline from title or description (highest confidence)
    // Catches patterns like "WASHINGTON (Reuters) - ..." or "Albania: Femicide cases..."
    // Rejects section labels like "Iran Live Updates:" or "Breaking News:"
    const titleDateline = DATELINE_PATTERN.exec(title);
    if (titleDateline && isGenuineDateline(titleDateline[1])) {
        candidates.push({ name: titleDateline[1].trim(), source: 'dateline' });
    }
    const descDateline = DATELINE_PATTERN.exec(description);
    if (descDateline && isGenuineDateline(descDateline[1])) {
        candidates.push({ name: descDateline[1].trim(), source: 'dateline' });
    }

    // 2. Comma-pair extraction ("Austin, Texas", "Springfield, Ill.")
    COMMA_PAIR_PATTERN.lastIndex = 0;
    let commaMatch;
    while ((commaMatch = COMMA_PAIR_PATTERN.exec(title)) !== null) {
        // Try the combined form first (e.g., "Springfield, Illinois")
        candidates.push({ name: `${commaMatch[1].trim()}, ${commaMatch[2].trim()}`, source: 'comma_pair' });
        // Also add the city part alone
        candidates.push({ name: commaMatch[1].trim(), source: 'comma_pair' });
    }
    COMMA_PAIR_PATTERN.lastIndex = 0;
    while ((commaMatch = COMMA_PAIR_PATTERN.exec(description)) !== null) {
        candidates.push({ name: `${commaMatch[1].trim()}, ${commaMatch[2].trim()}`, source: 'comma_pair' });
        candidates.push({ name: commaMatch[1].trim(), source: 'comma_pair' });
    }

    // 3. Regex passes on title
    for (const pattern of LOCATION_PATTERNS) {
        pattern.lastIndex = 0;
        let match;
        while ((match = pattern.exec(title)) !== null) {
            candidates.push({ name: match[1].trim(), source: 'regex' });
        }
    }

    // ── Score and sort candidates ────────────────────────────────────────────
    interface ScoredCandidate {
        name: string;
        key: string;
        source: string;
        typePriority: number;
        sourcePriority: number;
    }

    function computeScored(candidateList: Candidate[]): ScoredCandidate[] {
        const scored: ScoredCandidate[] = [];

        for (const { name: raw, source } of candidateList) {
            const candidate = cleanCandidate(raw);
            if (!candidate || candidate.length <= 2) continue;
            if (STOP_WORDS.has(candidate.toLowerCase())) continue;
            if (FALSE_POSITIVES.has(candidate.toLowerCase())) continue;

            const loc = disambiguate(candidate);
            let key = loc.toLowerCase();

            // Try progressively shorter sub-phrases if the full candidate isn't found
            // e.g. "Iowa county" → "Iowa", "New York City Council" → "New York City" → "New York"
            if (!KNOWN_LOCATIONS[key]) {
                const words = key.split(/\s+/);
                let found = false;
                for (let len = words.length - 1; len >= 1; len--) {
                    const sub = words.slice(0, len).join(' ');
                    if (sub.length > 2 && !STOP_WORDS.has(sub) && KNOWN_LOCATIONS[sub]) {
                        key = sub;
                        found = true;
                        break;
                    }
                }
                if (!found) continue;
            }

            let displayName = loc;
            if (key !== loc.toLowerCase()) {
                displayName = key.split(' ').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
            }

            const sourcePriority =
                source === 'dateline' ? 0 :
                source === 'comma_pair' ? 1 :
                source === 'regex' ? 2 :
                source === 'nlp' ? 3 : 4;

            scored.push({
                name: displayName,
                key,
                source,
                typePriority: locationPriority(key),
                sourcePriority,
            });
        }

        scored.sort((a, b) => {
            if (a.sourcePriority !== b.sourcePriority) return a.sourcePriority - b.sourcePriority;
            if (a.typePriority !== b.typePriority) return a.typePriority - b.typePriority;
            const popA = KNOWN_LOCATIONS[a.key]?.pop || 0;
            const popB = KNOWN_LOCATIONS[b.key]?.pop || 0;
            return popB - popA;
        });

        return scored;
    }

    // Try finding a match with dateline, comma, or regex first
    let bestCandidates = computeScored(candidates);

    // If no robust candidate was found, fall back to NLP parsing (which is ~2-5ms per string)
    if (bestCandidates.length === 0) {
        // 4. NLP pass on title
        const titlePlaces = nlp(title).places().out('array');
        if (titlePlaces && titlePlaces.length > 0) {
            for (const place of titlePlaces) {
                candidates.push({ name: place, source: 'nlp' });
            }
            bestCandidates = computeScored(candidates);
        }

        // 5. NLP fallback on description ONLY if title yielded no robust candidate
        if (bestCandidates.length === 0) {
            const descPlaces = nlp(description).places().out('array');
            if (descPlaces && descPlaces.length > 0) {
                for (const place of descPlaces) {
                    candidates.push({ name: place, source: 'nlp' });
                }
                bestCandidates = computeScored(candidates);
            }
        }
    }

    if (bestCandidates.length > 0) {
        return bestCandidates[0].name;
    }

    // 7a. Country abbreviation fallback — "U.S. casualties" → United States
    const abbrev = extractCountryAbbrev(title) || extractCountryAbbrev(description);
    if (abbrev && KNOWN_LOCATIONS[abbrev]) {
        const display = abbrev.split(' ').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
        return display;
    }

    // 7b. Demonym fallback — ONLY if zero physical locations were found
    // Check both title and description for demonyms (e.g. "South Korean police..." in desc)
    const demonym = extractDemonym(title) || extractDemonym(description);
    if (demonym && KNOWN_LOCATIONS[demonym]) {
        const display = demonym.split(' ').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
        return display;
    }

    // 8. Disabled last-resort API fallback
    // Sending unverified regex/comma-pair strings (like "Netflix, Hulu" or "MS exec") 
    // to the external Komoot API causes heavy rate-limiting and 10+ second pipeline delays.
    // With 78,000+ KNOWN_LOCATIONS locally, if a place isn't in the dict, it's 
    // almost certainly false-positive noise from the regex, not a real newsworthy city.
    return null;
}

// ── Geocoding ───────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// Try the local dictionary first, fall back to Photon API
export async function geocodeLocation(
    placeName: string
): Promise<{ lat: number; lon: number; displayName: string } | null> {
    const key = placeName.toLowerCase().trim();

    // Instant dictionary lookup
    const known = KNOWN_LOCATIONS[key];
    if (known) {
        return { lat: known.lat, lon: known.lon, displayName: placeName };
    }

    if (geoCache.has(key)) {
        return geoCache.get(key)!;
    }

    const geocodePromise = (async () => {
        try {
            // Use Photon (Komoot) — OSM-based, importance-weighted, typo-tolerant
            const url = `https://photon.komoot.io/api/?q=${encodeURIComponent(placeName)}&limit=1&lang=en`;

            const res = await fetch(url, {
                headers: {
                    'User-Agent': 'Seraphim/1.0',
                    'Accept-Language': 'en',
                },
                signal: AbortSignal.timeout(3000),
            });

            if (!res.ok) return null;

            const data = await res.json();
            if (!data || !data.features || data.features.length === 0) return null;

            const feature = data.features[0];
            const props = feature.properties || {};

            // Only accept actual populated places or admin boundaries.
            // Reject buildings, streets, highways, tourism spots, etc.
            const allowedOsmKeys = new Set(['place', 'boundary']);
            if (!allowedOsmKeys.has(props.osm_key)) {
                return null;
            }

            const [lon, lat] = feature.geometry.coordinates;
            const displayName = [props.name, props.state, props.country]
                .filter(Boolean)
                .join(', ');

            return {
                lat: lat as number,
                lon: lon as number,
                displayName: displayName || placeName,
            };
        } catch (err) {
            console.error(`geocoding failed for "${placeName}":`, err);
            return null;
        }
    })();

    geoCache.set(key, geocodePromise);
    return geocodePromise;
}

// ── Enrich news items ───────────────────────────────────────────────────────

export async function enrichItemsWithLocation(items: NewsItem[]): Promise<NewsItem[]> {
    const enriched: NewsItem[] = [];
    const usedCoords = new Map<string, number>();

    for (const item of items) {
        if (item.latitude !== undefined && item.longitude !== undefined) {
            enriched.push(item);
            continue;
        }

        let placeName = extractLocation(item.title, item.description);

        // If no location was extracted, check if the news source has a default location
        if (!placeName && item.source) {
            const srcKey = item.source.toLowerCase().trim();
            placeName = NEWS_SOURCE_DEFAULTS[srcKey] || null;
        }

        if (!placeName) {
            enriched.push(item);
            continue;
        }

        const key = placeName.toLowerCase().trim();
        const isDictionaryHit = KNOWN_LOCATIONS[key] !== undefined;
        const isCached = geoCache.has(key);

        const geo = await geocodeLocation(placeName);

        // Only sleep when we actually hit an external API
        if (!isDictionaryHit && !isCached) {
            console.log(`Hitting external API for: "${placeName}"`);
            await sleep(200);
        }

        if (geo) {
            // Apply jitter if another item already occupies the same coords
            const coordKey = `${geo.lat.toFixed(2)},${geo.lon.toFixed(2)}`;
            const count = usedCoords.get(coordKey) || 0;
            usedCoords.set(coordKey, count + 1);

            let lat = geo.lat;
            let lon = geo.lon;
            if (count > 0) {
                const angle = (count * 137.5 * Math.PI) / 180;
                const radius = 0.15 + (count * 0.05);
                lat += radius * Math.cos(angle);
                lon += radius * Math.sin(angle);
            }

            enriched.push({
                ...item,
                latitude: lat,
                longitude: lon,
                locationName: placeName,
            });
        } else {
            enriched.push(item);
        }
    }

    return enriched;
}
