import { NewsItem } from './types';
import nlp from 'compromise';

// load GeoNames data 
// generated by scripts/build-geodata.mjs from cities5000.txt + admin1CodesASCII.txt
import geoData from '../../data/geonames.json';

interface GeoCity { lat: number; lon: number; pop: number; cc: string }
interface GeoRegion { lat: number; lon: number; cc: string }

const geoCities: Record<string, GeoCity> = (geoData as Record<string, unknown>).cities as Record<string, GeoCity>;
const geoAdmin1: Record<string, GeoRegion> = (geoData as Record<string, unknown>).admin1 as Record<string, GeoRegion>;
const geoCountries: Record<string, GeoRegion> = ((geoData as Record<string, unknown>).countries || {}) as Record<string, GeoRegion>;

// build location dictionary
// priority: hardcoded overrides > GeoNames cities (population-weighted) > admin1 regions

interface LocationEntry {
    lat: number;
    lon: number;
    pop: number;
    type: 'city' | 'admin1' | 'country' | 'landmark';
}

export const KNOWN_LOCATIONS: Record<string, LocationEntry> = {};

// 1. Load GeoNames cities (population-weighted — highest pop wins on name collision)
for (const [key, city] of Object.entries(geoCities)) {
    if (key.length <= 2) continue;
    KNOWN_LOCATIONS[key] = { lat: city.lat, lon: city.lon, pop: city.pop, type: 'city' };
}

// 2. Load admin1 regions (states/provinces) — only if not already occupied by a large city
for (const [key, region] of Object.entries(geoAdmin1)) {
    if (key.length <= 2) continue;
    const existing = KNOWN_LOCATIONS[key];
    // Don't overwrite a city with > 500k pop with an admin1 region
    if (existing && existing.pop > 500000) continue;
    KNOWN_LOCATIONS[key] = { lat: region.lat, lon: region.lon, pop: 0, type: 'admin1' };
}

// 3. Countries from geonames.json — always override with their canonical centroids
// This loads 209+ country names (including Albania, Croatia, Senegal, etc.)
for (const [name, data] of Object.entries(geoCountries)) {
    if (name.length <= 2) continue;
    KNOWN_LOCATIONS[name] = { lat: data.lat, lon: data.lon, pop: 0, type: 'country' };
}

// 4. Hardcoded landmarks & conflict zones — highest priority overrides
// NOTE: continents (africa, asia, europe) are NOT here — they live in
// CONTINENT_FALLBACKS so they only match when nothing more specific is found.
const LANDMARKS: Record<string, { lat: number; lon: number }> = {
    'pentagon': { lat: 38.87, lon: -77.06 }, 'white house': { lat: 38.90, lon: -77.04 },
    'kremlin': { lat: 55.75, lon: 37.62 }, 'vatican': { lat: 41.90, lon: 12.45 },
    'gaza city': { lat: 31.50, lon: 34.47 }, 'west bank': { lat: 31.95, lon: 35.23 },
    'crimea': { lat: 44.95, lon: 34.10 }, 'donbas': { lat: 48.00, lon: 37.80 },
    'kharkiv': { lat: 49.99, lon: 36.23 }, 'odesa': { lat: 46.48, lon: 30.73 },
    'mariupol': { lat: 47.10, lon: 37.55 }, 'kherson': { lat: 46.64, lon: 32.62 },
    'aleppo': { lat: 36.20, lon: 37.16 }, 'mosul': { lat: 36.34, lon: 43.12 },
    'rafah': { lat: 31.30, lon: 34.25 }, 'khan younis': { lat: 31.35, lon: 34.30 },
    'kyiv': { lat: 50.45, lon: 30.52 }, 'kiev': { lat: 50.45, lon: 30.52 },
    'washington dc': { lat: 38.91, lon: -77.04 },
    'washington': { lat: 38.91, lon: -77.04 },
    'mediterranean': { lat: 35.0, lon: 18.0 },
    'mediterranean sea': { lat: 35.0, lon: 18.0 },
    'caspian sea': { lat: 41.0, lon: 50.0 },
    'darfur': { lat: 13.5, lon: 24.0 },
    'north darfur': { lat: 15.5, lon: 25.0 },
    'kurdistan': { lat: 37.0, lon: 43.0 },
    'falkland islands': { lat: -51.7, lon: -59.0 },
    'falklands': { lat: -51.7, lon: -59.0 },
    'siberia': { lat: 60.0, lon: 105.0 },
    'isfahan': { lat: 32.65, lon: 51.66 },
    'esfahan': { lat: 32.65, lon: 51.66 },
    'middle east': { lat: 29.29, lon: 41.05 },
    'west asia': { lat: 29.29, lon: 41.05 },
    'sanaa': { lat: 15.35, lon: 44.21 }, "sana'a": { lat: 15.35, lon: 44.21 },
    'sana': { lat: 15.35, lon: 44.21 },
    'strait of hormuz': { lat: 26.57, lon: 56.25 },
    'suez canal': { lat: 30.46, lon: 32.35 },
    'bab el-mandeb': { lat: 12.58, lon: 43.33 },
    'taiwan strait': { lat: 24.00, lon: 119.00 },
    'strait of malacca': { lat: 2.50, lon: 101.50 },
    'south china sea': { lat: 12.00, lon: 113.00 },
    'black sea': { lat: 43.00, lon: 35.00 },
    'red sea': { lat: 20.00, lon: 38.50 },
    'golan heights': { lat: 33.00, lon: 35.75 },
    'arctic': { lat: 71.0, lon: 25.0 },
    'antarctic': { lat: -82.0, lon: 0.0 },
    'antarctica': { lat: -82.0, lon: 0.0 },
    'southeast asia': { lat: 5.0, lon: 110.0 },
    'west coast': { lat: 37.77, lon: -122.42 },
    'east coast': { lat: 40.71, lon: -74.01 },
};

// Continent-level fallbacks — only used when no more-specific location is found.
// Kept separate so they don't collide with specific countries/cities
// (e.g. "africa" inside "South Africa").
const CONTINENT_FALLBACKS: Record<string, { lat: number; lon: number }> = {
    'europe': { lat: 54.5, lon: 15.2 },
    'africa': { lat: 8.7, lon: 20.9 },
    'asia': { lat: 34.0, lon: 100.0 },
    'oceania': { lat: -25.0, lon: 135.0 },
    'north america': { lat: 40.0, lon: -100.0 },
    'south america': { lat: -15.0, lon: -60.0 },
};

for (const [name, coords] of Object.entries(LANDMARKS)) {
    KNOWN_LOCATIONS[name] = { lat: coords.lat, lon: coords.lon, pop: 0, type: 'landmark' };
}

// continent fallbacks go into KNOWN_LOCATIONS too so geocodeLocation() can resolve them,
// but they are typed as 'landmark' and will be suppressed by continent-demotion logic.
for (const [name, coords] of Object.entries(CONTINENT_FALLBACKS)) {
    KNOWN_LOCATIONS[name] = { lat: coords.lat, lon: coords.lon, pop: 0, type: 'landmark' };
}

// demonym map
const DEMONYM_MAP: Record<string, string> = {
    'american': 'united states', 'chinese': 'china', 'russian': 'russia',
    'indian': 'india', 'japanese': 'japan', 'german': 'germany', 'deutschland': 'germany',
    'french': 'france', 'british': 'united kingdom', 'canadian': 'canada',
    'brazilian': 'brazil', 'australian': 'australia', 'mexican': 'mexico',
    'italian': 'italy', 'spanish': 'spain', 'korean': 'south korea',
    'iranian': 'iran', 'iraqi': 'iraq', 'syrian': 'syria',
    'turkish': 'turkey', 'israeli': 'israel', 'palestinian': 'palestine',
    'egyptian': 'egypt', 'saudi': 'saudi arabia', 'pakistani': 'pakistan',
    'afghan': 'afghanistan', 'nigerian': 'nigeria', 'kenyan': 'kenya',
    'ethiopian': 'ethiopia', 'sudanese': 'sudan', 'somali': 'somalia',
    'libyan': 'libya', 'yemeni': 'yemen', 'lebanese': 'lebanon',
    'jordanian': 'jordan', 'polish': 'poland', 'dutch': 'netherlands',
    'belgian': 'belgium', 'swedish': 'sweden', 'norwegian': 'norway',
    'danish': 'denmark', 'finnish': 'finland', 'greek': 'greece',
    'portuguese': 'portugal', 'swiss': 'switzerland', 'austrian': 'austria',
    'romanian': 'romania', 'hungarian': 'hungary', 'czech': 'czech republic',
    'indonesian': 'indonesia', 'filipino': 'philippines', 'vietnamese': 'vietnam',
    'thai': 'thailand', 'taiwanese': 'taiwan', 'malaysian': 'malaysia',
    'singaporean': 'singapore', 'argentinian': 'argentina', 'colombian': 'colombia',
    'chilean': 'chile', 'venezuelan': 'venezuela', 'peruvian': 'peru',
    'cuban': 'cuba', 'irish': 'ireland', 'scottish': 'scotland',
    'welsh': 'wales', 'moroccan': 'morocco', 'tunisian': 'tunisia',
    'algerian': 'algeria', 'ecuadorian': 'ecuador', 'bolivian': 'bolivia',
    'ukrainian': 'ukraine', 'georgian': 'georgia', 'armenian': 'armenia',
    'uruguayan': 'uruguay', 'paraguayan': 'paraguay', 'bahraini': 'bahrain',
    'qatari': 'qatar', 'kuwaiti': 'kuwait', 'omani': 'oman',
    'congolese': 'democratic republic of the congo', 'tanzanian': 'tanzania',
    'ugandan': 'uganda', 'rwandan': 'rwanda', 'cameroonian': 'cameroon',
    'senegalese': 'senegal', 'ghanaian': 'ghana', 'ivorian': 'ivory coast',
    'mozambican': 'mozambique', 'zimbabwean': 'zimbabwe', 'zambian': 'zambia',
    'namibian': 'namibia', 'botswanan': 'botswana', 'malawian': 'malawi',
    'nepalese': 'nepal', 'sri lankan': 'sri lanka', 'burmese': 'myanmar',
    'cambodian': 'cambodia', 'laotian': 'laos',
    // geographic adjectives (region/area → parent location)
    'siberian': 'siberia', 'crimean': 'crimea', 'arctic': 'arctic',
    'antarctic': 'antarctica', 'caribbean': 'caribbean',
    'balkan': 'balkans', 'scandinavian': 'scandinavia',
    'bavarian': 'germany', 'catalan': 'spain', 'tibetan': 'china',
};

// country abbreviation map
const COUNTRY_ABBREV_MAP: Record<string, string> = {
    'u.s.': 'united states', 'u.s.a.': 'united states', 'u.s': 'united states',
    'us': 'united states', 'america': 'united states',
    'u.k.': 'united kingdom', 'u.k': 'united kingdom', 'uk': 'united kingdom',
    'u.a.e.': 'united arab emirates', 'uae': 'united arab emirates',
    'u.n.': '__skip__',  // Not a country
    'e.u.': '__skip__',  // Not a country
    'd.c.': 'washington dc',
};

// patterns

// regex for standard datelines (e.g. "WASHINGTON (Reuters) - ")
const DATELINE_PATTERN = /^(?:\[[^\]]+\]\s*)?([A-Z][A-Za-z\s]+?)\s*(?:\([^)]+\))?\s*(?:-|—|–|:)\s+/;

// Words that indicate a section/topic label rather than a geographic dateline.
// When a dateline candidate contains any of these, it's treated as a section header
// (e.g. "Iran Live Updates:" is a topic label, not a dateline like "TEHRAN:").
const DATELINE_NOISE_WORDS = new Set([
    'live', 'updates', 'update', 'breaking', 'latest', 'analysis',
    'opinion', 'editorial', 'exclusive', 'recap', 'roundup', 'review',
    'briefing', 'explainer', 'report', 'summary', 'watch', 'alert',
    'blog', 'tracker', 'results', 'polls', 'podcast', 'newsletter',
    'centcom', 'eucom', 'africom', 'indopacom', 'southcom', 'northcom',
]);

// Optimized module-level regexes to avoid re-compilation
const EMOJI_STRIP = /[\u{1F000}-\u{1FFFF}\u{2600}-\u{27BF}\u{FE00}-\u{FE0F}\u{200D}\u{20E3}\u{E0020}-\u{E007F}\u{1F1E0}-\u{1F1FF}\u{2702}-\u{27B0}\u{FE0E}]/gu;
const METADATA_COUNTRY_REGEX = /\bCountry:\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+){0,3})/;

// "City, State" or "City, Country" comma-pair pattern
const COMMA_PAIR_PATTERN = /([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)*),\s*([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)*)/g;

// Unicode-aware letter class for location capture groups
// Captures accented characters (e.g. Zaporizhzhia, São Paulo, Zürich)
const L = '[a-zA-Z\u00C0-\u024F]'; // a single letter including accented
const LOC = `[A-Z\u00C0-\u024F]${L}+(?:\\s+[A-Z\u00C0-\u024F]${L}+){0,3}`; // multi-word location

// regex patterns to pull "in Place", "from Place", "bombards Place", etc.
// Verbs use explicit [Aa] style casing so headline capitals match without /i flag,
// which would break the [A-Z] location-capture group.
const LOCATION_PATTERNS = [
    // Prepositions — [Ii][Nn] style casing so headline capitals ("In Syria") match
    new RegExp(`\\b[Ii]n\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ii]n\\s+[Tt]he\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ff]rom\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Nn]ear\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Aa]cross\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Oo]ff\\s+(?:[Tt]he\\s+[Cc]oast\\s+[Oo]f\\s+)?(${LOC})`, 'g'),
    new RegExp(`\\b[Tt]o\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Aa]t\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Tt]owards?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ww]ith\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Oo]ver\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Oo]n\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:[Cc]ity|[Tt]own|[Pp]rovince|[Ss]tate|[Rr]egion|[Vv]illage|[Cc]enter|[Cc]entre)\\s+[Oo]f\\s+(${LOC})`, 'g'),

    // Present-tense action verbs
    new RegExp(`\\b[Hh]its?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ss]trikes?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Aa]ttacks?\\s+(?:[Oo]n\\s+)?(${LOC})`, 'g'),
    new RegExp(`\\b[Ff]ighting\\s+in\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ww]ar\\s+in\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Cc]risis\\s+in\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ii]nvades?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Oo]ccupied\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Bb]ombards?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ss]hells?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Tt]argets?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ss]eizes?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Cc]aptures?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Rr]aids?\\s+(?:[Oo]n\\s+)?(${LOC})`, 'g'),
    new RegExp(`\\b[Bb]esieges?\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ff]lees?\\s+to\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Dd]eploys?\\s+to\\s+(${LOC})`, 'g'),

    // Past-tense variants
    new RegExp(`\\b[Aa]ttacked\\s+in\\s+(?:the\\s+)?(${LOC})`, 'g'),
    new RegExp(`\\b[Tt]argeted\\s+(?:in\\s+)?(?:the\\s+)?(${LOC})`, 'g'),
    new RegExp(`\\bagainst\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:mayor|governor|leader)\\s+of\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Ss]helled\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Bb]ombed\\s+(${LOC})`, 'g'),
];

// Action-target patterns — these specifically extract the TARGET/OBJECT of an action.
// They get a priority boost (source='action_target') to outrank the actor/demonym.
// e.g. "Israeli strikes on Yemen" → extracts "Yemen" as action_target
const ACTION_TARGET_PATTERNS = [
    new RegExp(`\\b(?:strikes?|struck)\\s+(?:on|in|against)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:attack|attacked|attacks)\\s+(?:on|in|against)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:fired|fires?|launches?|launched)\\s+(?:at|on|into|towards?)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:missile|rocket|drone)\\s+(?:attack|strike)s?\\s+(?:on|against|in)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:hit|hits|hitting)\\s+(?:a\\s+)?(?:.*?\\s+)?(?:in|near)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:bombed|bombing|bombs?)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:war|conflict)\\s+(?:on|in|with|against)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:sanctions?)\\s+(?:on|against)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:invad(?:es?|ed|ing))\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:sunk|sank|intercept(?:s|ed|ing)?)\\s+.*?\\b(?:in|near|off)\\s+(${LOC})`, 'g'),
    new RegExp(`(${LOC})\\s+(?:is|are)\\s+under\\s+(?:heavy\\s+)?(?:attack|fire|bombardment|siege)`, 'g'),
    new RegExp(`\\b(?:ambassador|envoy)\\s+to\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:war|conflict)\\s+(?:on|in|with|against)\\s+(${LOC})`, 'g'),
    new RegExp(`\\b(?:Weapons|weapons|HIMARS|arms)\\s+on\\s+(${LOC})`, 'g'),
    new RegExp(`\\b[Aa]ir\\s+[Ss]trikes?\\s+(?:on|in|against|over)\\s+(${LOC})`, 'g'),
    // "intercepting X's ..." type patterns
    new RegExp(`\\b(?:intercept(?:s|ed|ing)?)\\s+(${LOC})`, 'g'),
];

// words regex might catch but aren't locations
const STOP_WORDS = new Set([
    // months & days
    'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august',
    'september', 'october', 'november', 'december', 'monday', 'tuesday',
    'wednesday', 'thursday', 'friday', 'saturday', 'sunday',

    // seasons
    'spring', 'summer', 'fall', 'winter',

    // determiners & pronouns
    'the', 'this', 'that', 'these', 'those', 'what', 'which', 'who', 'how',
    'just', 'new', 'more', 'most', 'some', 'many', 'much', 'its', 'his', 'her',
    'their', 'our', 'all', 'one', 'two', 'three', 'four', 'five',

    // news & media terms
    'congress', 'senate', 'parliament', 'reuters', 'associated',
    'press', 'exclusive', 'breaking', 'update', 'live', 'latest',
    'report', 'reports', 'analysis', 'opinion', 'editorial',

    // common false-positive capitalized words
    'trump', 'biden', 'putin', 'modi', 'macron', 'scholz', 'zelenskyy',
    'zelensky', 'netanyahu', 'xi', 'obama', 'pope', 'elon', 'musk',
    'democrats', 'republicans', 'nato', 'opec', 'who', 'fbi', 'cia',
    'deal', 'record', 'back', 'first', 'second', 'third', 'over',
    'after', 'before', 'major', 'global', 'world', 'international',
    'north', 'south', 'east', 'west', 'says', 'say', 'said',
    'each', 'every', 'both', 'other', 'another', 'such',
    'high', 'higher', 'low', 'lower', 'big', 'small', 'long',
    'war', 'peace', 'crisis', 'today', 'yesterday', 'tomorrow',
    'government', 'president', 'minister', 'prime', 'general',
    'military', 'army', 'force', 'forces', 'troops', 'police',
    'court', 'supreme', 'justice', 'law', 'bill', 'act',
    'company', 'companies', 'stocks', 'market', 'markets',
    'people', 'officials', 'sources', 'leaders', 'workers',

    // space agencies & organizations (false positives from "from NASA", etc.)
    'nasa', 'esa', 'spacex', 'jaxa', 'isro', 'roscosmos',
    'un', 'united nations', 'imf', 'interpol',

    // military commands & coalitions (organizational names, not locations)
    'centcom', 'eucom', 'africom', 'indopacom', 'southcom', 'northcom',
    'socom', 'transcom', 'stratcom', 'cybercom', 'spacecom',

    // celestial bodies (NLP/regex catches "Venus", "Mars", etc.)
    'moon', 'sun', 'venus', 'mars', 'jupiter', 'saturn', 'mercury',
    'neptune', 'uranus', 'pluto', 'earth', 'lunar', 'solar',
    'asteroid', 'comet', 'nebula', 'galaxy', 'orbit', 'spacecraft',

    // generic geographic words that aren't specific locations
    'island', 'islands', 'peninsula', 'continent', 'region', 'area',
    'coast', 'mountain', 'river', 'lake', 'ocean', 'sea', 'bay', 'gulf',

    // ambiguous short words that collide with real places
    // "Man" → city in Ivory Coast but in news it's almost always "Man City", "Man United"
    'man',

    // brand/person names
    'humble', 'bowen',

    // structured metadata labels (ReliefWeb: "Country: Yemen Source: WFP")
    'country', 'source', 'category', 'theme', 'format', 'topic',

    // timezone abbreviations that get caught by comma-pair ("ET, March")
    'et', 'pt', 'ct', 'mt', 'est', 'pst', 'cst', 'mst', 'gmt', 'utc',

    // ambiguous partial place fragments (NLP splits "Hong Kong" → "Hong")
    'hong', 'kong', 'abu', 'san', 'los', 'las', 'das', 'del', 'der',
    // short person name fragments NLP catches as locations
    'jos',

    // "America" as standalone is too ambiguous — already handled by COUNTRY_ABBREV_MAP → "united states"
    'america',
]);

// false positives
// names, brands, and sports teams that NLP/regex detect as geographic places.
// these get checked against BOTH the raw candidate AND the disambiguated key.
const FALSE_POSITIVES = new Set([
    // multi-word names where the first word is also a real place
    'paris hilton', 'jackson hole', 'georgia tech',
    'chelsea clinton', 'chelsea handler', 'virginia woolf',

    // sports teams (these match city names but are rarely used as location references)
    'arsenal', 'chelsea fc', 'manchester united', 'manchester city',
    'real madrid', 'bayern munich', 'juventus', 'napoli',
    'tottenham', 'everton', 'wolverhampton', 'newcastle united',

    // brands / companies that are also place names
    'amazon', 'apple', 'oracle', 'adobe', 'cisco',

    // social media source names & handles that regex/NLP might pick up
    'liveuamap', 'nitter', 'osint',
    'geoconfirmed', 'intelcrab', 'auroraintel', 'osinttechnical',

    // common compound false positives from news headlines
    'research roundup', 'audio long read', 'author correction',
    'weekend of war', 'morning edition', 'evening update',
    'daily briefing', 'weekly roundup', 'year in review',

    // conflict / event names that NLP detects as places
    'gulf war', 'cold war', 'world war', 'civil war', 'arab spring',
    'iron dome', 'iron curtain',
]);

// news source default locations
// fallback locations for well-known news providers whose articles often lack
// extractable geographic context (e.g. "NASA discovers new exoplanet").
// these are used as a LAST resort when no location can be found at all.
const NEWS_SOURCE_DEFAULTS: Record<string, string> = {
    'nasa': 'Washington DC',
    'nature': 'London',
    'ars technica': 'San Francisco',
    'the verge': 'New York',
    'who': 'Geneva',
};

// helper functions

// normalize unicode diacritics/accents to ascii equivalents
// e.g. "Irán" → "Iran", "São Paulo" → "Sao Paulo", "Zürich" → "Zurich"
function normalizeAccents(s: string): string {
    return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

/**
 * Normalizes a location string to Title Case.
 * Handles special cases like "DC" and hyphenated names.
 */
function toTitleCase(s: string): string {
    if (!s) return s;
    return s.toLowerCase().split(' ').map(word => {
        if (word === 'dc') return 'DC';
        // Handle hyphenated words like "Port-au-Prince" or "Guinea-Bissau"
        if (word.includes('-')) {
            return word.split('-')
                .map(part => part.charAt(0).toUpperCase() + part.slice(1))
                .join('-');
        }
        return word.charAt(0).toUpperCase() + word.slice(1);
    }).join(' ');
}

// clean a candidate: strip possessives, trailing punctuation, dashes, etc.
function cleanCandidate(raw: string): string {
    let s = raw.trim();
    s = s.replace(/['\u2019]s\b/g, '');      // "Canada's" → "Canada"
    s = s.replace(/['\u2019]s$/g, '');        // trailing possessive at end of string
    s = s.replace(/[.,;:!?"')]+$/, '');       // trailing punctuation
    s = s.replace(/^["'(\u2014\u2013\-]+/, ''); // leading punctuation + em-dash/en-dash/hyphen
    s = s.replace(/[\u2014\u2013\-]+$/, '');   // trailing em-dash/en-dash/hyphen
    return s.trim();
}

// safe disambiguate: check exact match ONLY. No destructive word-chopping.
// if the full phrase is in the dictionary, return it. Otherwise return as-is.
// also tries accent-normalized form.
function disambiguate(candidate: string): string {
    const key = candidate.toLowerCase().trim();
    if (KNOWN_LOCATIONS[key]) return candidate;
    // Try accent-normalized form (e.g. "Irán" → "iran")
    const normalized = normalizeAccents(key);
    if (normalized !== key && KNOWN_LOCATIONS[normalized]) {
        // Return the display name that matches the dictionary key
        return normalizeAccents(candidate);
    }
    return candidate;
}

// try to resolve a demonym ("Chinese" → "China")
function extractDemonym(text: string): string | null {
    const words = text.split(/[\s\-]+/);
    for (const word of words) {
        const lower = word.toLowerCase().replace(/[^a-z]/g, '');
        if (DEMONYM_MAP[lower]) {
            return DEMONYM_MAP[lower];
        }
        if (lower.endsWith('s') && DEMONYM_MAP[lower.slice(0, -1)]) {
            return DEMONYM_MAP[lower.slice(0, -1)];
        }
    }
    return null;
}

// try to resolve country abbreviations in text ("U.S." → "united states")
// keeps periods so we can match "U.S." properly, unlike demonyms which strip punctuation
function extractCountryAbbrev(text: string): string | null {
    // split on whitespace and hyphens
    const tokens = text.split(/[\s\-]+/);
    for (const token of tokens) {
        // Normalize: lowercase, strip trailing commas/colons/semicolons but keep periods
        const cleaned = token.toLowerCase().replace(/[,;:!?'")\]]+$/, '').replace(/^['"(\[]+/, '');
        const mapped = COUNTRY_ABBREV_MAP[cleaned];
        if (mapped && mapped !== '__skip__') {
            return mapped;
        }
    }
    return null;
}

// determine the priority type of a location (lower = more specific = better)
// for country/city name collisions (e.g. "Albania" the country vs "Albania" the city
// in Colombia), the country wins unless the city has >1M population.
function locationPriority(key: string): number {
    const entry = KNOWN_LOCATIONS[key];
    if (!entry) return 99;
    switch (entry.type) {
        case 'landmark': return 0;
        case 'city': return entry.pop > 1000000 ? 2 : 6;
        case 'country': return 4;
        case 'admin1': return 8;
        default: return 99;
    }
}

// Continent name set — used to suppress continent matches when specific locations exist
const CONTINENT_NAMES = new Set(Object.keys(CONTINENT_FALLBACKS));

// Build a sorted (longest-first) list of multi-word location names for compound scanning.
// This catches "South Africa", "New Zealand", "Sri Lanka", "West Coast" etc. as whole units.
// Build a Set of multi-word locations for O(1) sliding-window scanning. 
const MULTI_WORD_LOC_SET = new Set(Object.keys(KNOWN_LOCATIONS).filter(k => k.includes(' ')));

// main extraction

interface Candidate {
    name: string;
    source: 'dateline' | 'comma_pair' | 'regex' | 'direct_scan' | 'nlp' | 'demonym' | 'abbrev' | 'action_target' | 'compound_scan';
    placement: 'title' | 'description';
}

export function extractLocation(title: string, description: string): { match: string | null; candidates: string[] } {
    // Strip emoji and normalize whitespace
    title = title.replace(EMOJI_STRIP, ' ').replace(/\s+/g, ' ').trim();
    description = description.replace(EMOJI_STRIP, ' ').replace(/\s+/g, ' ').trim();

    const candidates: Candidate[] = [];

    // helper: check if a dateline candidate is a genuine geographic dateline
    // vs a section label like "Iran Live Updates:" or "Breaking News:"
    function isGenuineDateline(raw: string): boolean {
        const words = raw.toLowerCase().split(/\s+/);
        // reject section labels ("Iran Live Updates:")
        if (words.some(w => DATELINE_NOISE_WORDS.has(w))) return false;
        // reject continent-level datelines ("Africa: Morocco...")
        const key = raw.toLowerCase().trim();
        if (CONTINENT_NAMES.has(key)) return false;
        return true;
    }

    // 1a. structured metadata pattern (ReliefWeb, humanitarian feeds)
    let metaMatch = METADATA_COUNTRY_REGEX.exec(title);
    if (metaMatch) candidates.push({ name: metaMatch[1].trim(), source: 'dateline', placement: 'title' });
    metaMatch = METADATA_COUNTRY_REGEX.exec(description);
    if (metaMatch) candidates.push({ name: metaMatch[1].trim(), source: 'dateline', placement: 'description' });

    // 1b. dateline from title or description (highest confidence)
    // catches patterns like "WASHINGTON (Reuters) - ..." or "Albania: Femicide cases..."
    // rejects section labels like "Iran Live Updates:" or "Breaking News:"
    const titleDateline = DATELINE_PATTERN.exec(title);
    if (titleDateline && isGenuineDateline(titleDateline[1])) {
        candidates.push({ name: titleDateline[1].trim(), source: 'dateline', placement: 'title' });
    }
    const descDateline = DATELINE_PATTERN.exec(description);
    if (descDateline && isGenuineDateline(descDateline[1])) {
        candidates.push({ name: descDateline[1].trim(), source: 'dateline', placement: 'description' });
    }

    // 1c. title-subject country extraction
    // Headlines often start with the subject country: "Paraguay Space Program", "Venezuela opens..."
    // Scan the start of the title for a known country/location name (1-3 words).
    {
        // Strip leading non-letter characters (emoji, flags, etc.)
        const strippedTitle = title.replace(/^[^a-zA-Z\u00C0-\u024F]+/, '');
        const titleWords = strippedTitle.split(/\s+/);
        // Try 3-word, 2-word, then 1-word prefix matches
        for (let len = Math.min(3, titleWords.length); len >= 1; len--) {
            const prefix = titleWords.slice(0, len).join(' ');
            const cleaned = cleanCandidate(prefix);
            const key = normalizeAccents(cleaned.toLowerCase());
            if (key.length > 2 && KNOWN_LOCATIONS[key] && !STOP_WORDS.has(key) && !CONTINENT_NAMES.has(key)) {
                // Use 'demonym' source so preposition-based matches outrank title-subject
                candidates.push({ name: cleaned, source: 'demonym', placement: 'title' });
                break;
            }
        }
    }

    // 2. comma-pair extraction ("Austin, Texas", "Springfield, Ill.")
    COMMA_PAIR_PATTERN.lastIndex = 0;
    let commaMatch;
    while ((commaMatch = COMMA_PAIR_PATTERN.exec(title)) !== null) {
        candidates.push({ name: `${commaMatch[1].trim()}, ${commaMatch[2].trim()}`, source: 'comma_pair', placement: 'title' });
        candidates.push({ name: commaMatch[1].trim(), source: 'comma_pair', placement: 'title' });
    }
    COMMA_PAIR_PATTERN.lastIndex = 0;
    while ((commaMatch = COMMA_PAIR_PATTERN.exec(description)) !== null) {
        candidates.push({ name: `${commaMatch[1].trim()}, ${commaMatch[2].trim()}`, source: 'comma_pair', placement: 'description' });
        candidates.push({ name: commaMatch[1].trim(), source: 'comma_pair', placement: 'description' });
    }

    // 3. Optimized dictionary scan for multi-word place names (replaces expensive O(N) regex loop)
    const fastDictionaryScan = (text: string, placement: 'title' | 'description') => {
        const words = text.split(/[\s,.;:!?()\[\]"']+/).filter(w => w.length > 0);
        for (let i = 0; i < words.length; i++) {
            for (let len = Math.min(4, words.length - i); len >= 2; len--) {
                const slice = words.slice(i, i + len).join(' ');
                const cleaned = cleanCandidate(slice);
                if (cleaned.length <= 3) continue;
                const key = normalizeAccents(cleaned.toLowerCase());
                if (MULTI_WORD_LOC_SET.has(key)) {
                    candidates.push({ name: cleaned, source: 'compound_scan', placement });
                }
            }
        }
    };
    fastDictionaryScan(title, 'title');
    fastDictionaryScan(description, 'description');

    // 4. regex passes on title AND description
    for (const pattern of LOCATION_PATTERNS) {
        pattern.lastIndex = 0;
        let match;
        while ((match = pattern.exec(title)) !== null) {
            candidates.push({ name: match[1].trim(), source: 'regex', placement: 'title' });
        }
        pattern.lastIndex = 0;
        while ((match = pattern.exec(description)) !== null) {
            candidates.push({ name: match[1].trim(), source: 'regex', placement: 'description' });
        }
    }

    // 4b. action-target patterns (highest confidence for event location)
    for (const pattern of ACTION_TARGET_PATTERNS) {
        pattern.lastIndex = 0;
        let match;
        while ((match = pattern.exec(title)) !== null) {
            candidates.push({ name: match[1].trim(), source: 'action_target', placement: 'title' });
        }
        pattern.lastIndex = 0;
        while ((match = pattern.exec(description)) !== null) {
            candidates.push({ name: match[1].trim(), source: 'action_target', placement: 'description' });
        }
    }

    // 5. early fallback promotions
    const titleAbbrev = extractCountryAbbrev(title);
    if (titleAbbrev) candidates.push({ name: titleAbbrev, source: 'abbrev', placement: 'title' });
    const descAbbrev = extractCountryAbbrev(description);
    if (descAbbrev) candidates.push({ name: descAbbrev, source: 'abbrev', placement: 'description' });

    const titleDemonym = extractDemonym(title);
    if (titleDemonym) candidates.push({ name: titleDemonym, source: 'demonym', placement: 'title' });
    const descDemonym = extractDemonym(description);
    if (descDemonym) candidates.push({ name: descDemonym, source: 'demonym', placement: 'description' });

    // 6. Optimized direct landmark scan (replaces regex loop)
    const scanLandmarks = (text: string, placement: 'title' | 'description') => {
        const words = text.split(/[\s,.;:!?()\[\]"']+/).filter(w => w.length > 0);
        for (let i = 0; i < words.length; i++) {
            for (let len = Math.min(4, words.length - i); len >= 1; len--) {
                const slice = words.slice(i, i + len).join(' ');
                const cleaned = cleanCandidate(slice);
                const key = normalizeAccents(cleaned.toLowerCase());
                if (LANDMARKS[key]) {
                    candidates.push({ name: cleaned, source: 'direct_scan', placement });
                }
            }
        }
    };
    scanLandmarks(title, 'title');
    scanLandmarks(description, 'description');

    // score and sort candidates
    interface ScoredCandidate {
        name: string;
        key: string;
        source: string;
        score: number;
    }

    function computeScored(candidateList: Candidate[]): ScoredCandidate[] {
        const scored: ScoredCandidate[] = [];

        for (const { name: raw, source, placement } of candidateList) {
            const candidate = cleanCandidate(raw);
            if (!candidate || candidate.length <= 2) continue;
            if (STOP_WORDS.has(candidate.toLowerCase())) continue;
            if (FALSE_POSITIVES.has(candidate.toLowerCase())) continue;

            const loc = disambiguate(candidate);
            let key = normalizeAccents(loc.toLowerCase());

            // try progressively shorter sub-phrases if the full candidate isn't found
            // e.g. "Iowa county" → "Iowa", "New York City Council" → "New York City" → "New York"
            if (!KNOWN_LOCATIONS[key]) {
                const words = key.split(/\s+/);
                let found = false;
                for (let len = words.length - 1; len >= 1; len--) {
                    const sub = words.slice(0, len).join(' ');
                    if (sub.length > 2 && !STOP_WORDS.has(sub) && KNOWN_LOCATIONS[sub]) {
                        key = sub;
                        found = true;
                        break;
                    }
                }
                // candidates not found in KNOWN_LOCATIONS are dropped unless they come
                // from high-confidence sources that are guaranteed to resolve
                // (abbrev & demonym always produce dictionary keys like "united states").
                // NLP and direct_scan candidates that aren't in the dictionary are noise.
                if (!found && source !== 'abbrev' && source !== 'demonym') continue;
            }

            const displayName = toTitleCase(loc);

            const wPlacement = placement === 'title' ? 0 : 4;
            let wSource = 0;
            switch(source) {
                case 'action_target': wSource = -2; break; // highest priority — these are event locations
                case 'dateline': wSource = 0; break;
                case 'compound_scan': wSource = 1; break;
                case 'comma_pair': wSource = 1; break;
                case 'regex': wSource = 2; break;
                case 'direct_scan': wSource = 3; break;
                case 'demonym': case 'abbrev': wSource = 5; break;
                case 'nlp': wSource = 6; break;
            }
            const wType = locationPriority(key);

            // Penalty for continent-level matches — they should only win if nothing specific exists
            const continentPenalty = CONTINENT_NAMES.has(key) ? 20 : 0;

            // Penalty for "superpowers" (US, UK) via ANY extraction source.
            // In multi-country headlines ("US strikes on Iran", "Russia Claims X In Syria"),
            // the event location is almost always more newsworthy than the actor.
            const SUPERPOWER_KEYS = new Set(['united states', 'united kingdom']);
            const superpowerPenalty = SUPERPOWER_KEYS.has(key) ? 10 : 0;

            scored.push({
                name: displayName,
                key,
                source,
                score: wPlacement + wSource + wType + continentPenalty + superpowerPenalty
            });
        }

        scored.sort((a, b) => {
            if (a.score !== b.score) return a.score - b.score;
            const popA = KNOWN_LOCATIONS[a.key]?.pop || 0;
            const popB = KNOWN_LOCATIONS[b.key]?.pop || 0;
            return popB - popA;
        });

        return scored;
    }

    // try finding a match with dateline, comma, or regex first
    let bestCandidates = computeScored(candidates);

    // if no robust candidate was found, fall back to NLP parsing (which is ~2-5ms per string)
    if (bestCandidates.length === 0) {
        // 4. NLP pass on title
        const titlePlaces = nlp(title).places().out('array');
        if (titlePlaces && titlePlaces.length > 0) {
            for (const place of titlePlaces) {
                candidates.push({ name: place, source: 'nlp', placement: 'title' });
            }
            bestCandidates = computeScored(candidates);
        }

        // 5. NLP fallback on description ONLY if title yielded no robust candidate
        if (bestCandidates.length === 0) {
            const descPlaces = nlp(description).places().out('array');
            if (descPlaces && descPlaces.length > 0) {
                for (const place of descPlaces) {
                    candidates.push({ name: place, source: 'nlp', placement: 'description' });
                }
                bestCandidates = computeScored(candidates);
            }
        }
    }

    if (bestCandidates.length > 0) {
        return { match: bestCandidates[0].name, candidates: bestCandidates.map(c => c.name) };
    }

    // 7c. Optimized direct country name fallback
    const scanCountries = (text: string) => {
        const words = text.split(/[\s,.;:!?()\[\]"']+/).filter(w => w.length > 0);
        for (let i = 0; i < words.length; i++) {
            for (let len = Math.min(4, words.length - i); len >= 1; len--) {
                const slice = words.slice(i, i + len).join(' ');
                const cleaned = cleanCandidate(slice);
                const key = normalizeAccents(cleaned.toLowerCase());
                if (geoCountries[key]) {
                    const display = toTitleCase(key);
                    return { match: display, candidates: [display] };
                }
            }
        }
        return null;
    };

    const countryMatch = scanCountries(title) || scanCountries(description);
    if (countryMatch) return countryMatch;

    // 7d. Optimized continent fallback — last resort when absolutely nothing else matches
    const scanContinents = (text: string) => {
        const words = text.split(/[\s,.;:!?()\[\]"']+/).filter(w => w.length > 0);
        for (let i = 0; i < words.length; i++) {
            for (let len = Math.min(4, words.length - i); len >= 1; len--) {
                const slice = words.slice(i, i + len).join(' ');
                const cleaned = cleanCandidate(slice);
                const key = normalizeAccents(cleaned.toLowerCase());
                if (CONTINENT_FALLBACKS[key]) {
                    const display = toTitleCase(key);
                    return { match: display, candidates: [display] };
                }
            }
        }
        return null;
    };

    const continentMatch = scanContinents(title) || scanContinents(description);
    if (continentMatch) return continentMatch;

    // 8. No external API fallback — dictionary-only geocoding.
    return { match: null, candidates: [] };
}

// geocoding

// dictionary-only geocoding. no external API calls.
// the extraction pipeline guarantees all returned matches exist in KNOWN_LOCATIONS.
export async function geocodeLocation(
    placeName: string
): Promise<{ lat: number; lon: number; displayName: string } | null> {
    const key = normalizeAccents(placeName.toLowerCase().trim());

    // instant dictionary lookup
    const known = KNOWN_LOCATIONS[key];
    if (known) {
        return { lat: known.lat, lon: known.lon, displayName: placeName };
    }

    // not in dictionary — return null (no external API fallback)
    return null;
}

// enrich news items

export async function enrichItemsWithLocation(items: NewsItem[]): Promise<NewsItem[]> {
    const enriched: NewsItem[] = [];
    const usedCoords = new Map<string, number>();

    for (const item of items) {
        if (item.latitude !== undefined && item.longitude !== undefined) {
            enriched.push(item);
            continue;
        }

        const ext = extractLocation(item.title, item.description);
        let placeName = ext.match;
        let candidates = ext.candidates;

        // if no location was extracted, check if the news source has a default location
        if (!placeName && item.source) {
            const srcKey = item.source.toLowerCase().trim();
            placeName = NEWS_SOURCE_DEFAULTS[srcKey] || null;
            if (placeName) candidates = [placeName]; // source default
        }

        if (!placeName) {
            enriched.push({ ...item, foundLocations: candidates });
            continue;
        }

        const geo = await geocodeLocation(placeName);

        if (geo) {
            // apply jitter if another item already occupies the same coords
            const coordKey = `${geo.lat.toFixed(2)},${geo.lon.toFixed(2)}`;
            const count = usedCoords.get(coordKey) || 0;
            usedCoords.set(coordKey, count + 1);

            let lat = geo.lat;
            let lon = geo.lon;
            if (count > 0) {
                const angle = (count * 137.5 * Math.PI) / 180;
                const radius = 0.15 + (count * 0.05);
                lat += radius * Math.cos(angle);
                lon += radius * Math.sin(angle);
            }

            enriched.push({
                ...item,
                latitude: lat,
                longitude: lon,
                locationName: placeName,
                foundLocations: candidates,
            });
        } else {
            enriched.push({ ...item, foundLocations: candidates });
        }
    }

    return enriched;
}
