/**
 * Constants and lookup maps for the geocoding engine.
 */

export const LANDMARKS: Record<string, { lat: number; lon: number }> = {
    'pentagon': { lat: 38.87, lon: -77.06 }, 'white house': { lat: 38.90, lon: -77.04 },
    'kremlin': { lat: 55.75, lon: 37.62 }, 'vatican': { lat: 41.90, lon: 12.45 },
    'gaza city': { lat: 31.50, lon: 34.47 }, 'west bank': { lat: 31.95, lon: 35.23 },
    'crimea': { lat: 44.95, lon: 34.10 }, 'donbas': { lat: 48.00, lon: 37.80 },
    'kharkiv': { lat: 49.99, lon: 36.23 }, 'odesa': { lat: 46.48, lon: 30.73 },
    'mariupol': { lat: 47.10, lon: 37.55 }, 'kherson': { lat: 46.64, lon: 32.62 },
    'aleppo': { lat: 36.20, lon: 37.16 }, 'mosul': { lat: 36.34, lon: 43.12 },
    'rafah': { lat: 31.30, lon: 34.25 }, 'khan younis': { lat: 31.35, lon: 34.30 },
    'kyiv': { lat: 50.45, lon: 30.52 }, 'kiev': { lat: 50.45, lon: 30.52 },
    'washington dc': { lat: 38.91, lon: -77.04 },
    'washington': { lat: 38.91, lon: -77.04 },
    'mediterranean': { lat: 35.0, lon: 18.0 },
    'mediterranean sea': { lat: 35.0, lon: 18.0 },
    'caspian sea': { lat: 41.0, lon: 50.0 },
    'darfur': { lat: 13.5, lon: 24.0 },
    'north darfur': { lat: 15.5, lon: 25.0 },
    'kurdistan': { lat: 37.0, lon: 43.0 },
    'falkland islands': { lat: -51.7, lon: -59.0 },
    'falklands': { lat: -51.7, lon: -59.0 },
    'siberia': { lat: 60.0, lon: 105.0 },
    'isfahan': { lat: 32.65, lon: 51.66 },
    'esfahan': { lat: 32.65, lon: 51.66 },
    'middle east': { lat: 29.29, lon: 41.05 },
    'west asia': { lat: 29.29, lon: 41.05 },
    'sanaa': { lat: 15.35, lon: 44.21 }, "sana'a": { lat: 15.35, lon: 44.21 },
    'sana': { lat: 15.35, lon: 44.21 },
    'strait of hormuz': { lat: 26.57, lon: 56.25 },
    'suez canal': { lat: 30.46, lon: 32.35 },
    'bab el-mandeb': { lat: 12.58, lon: 43.33 },
    'taiwan strait': { lat: 24.00, lon: 119.00 },
    'strait of malacca': { lat: 2.50, lon: 101.50 },
    'south china sea': { lat: 12.00, lon: 113.00 },
    'black sea': { lat: 43.00, lon: 35.00 },
    'red sea': { lat: 20.00, lon: 38.50 },
    'golan heights': { lat: 33.00, lon: 35.75 },
    'arctic': { lat: 71.0, lon: 25.0 },
    'antarctic': { lat: -82.0, lon: 0.0 },
    'antarctica': { lat: -82.0, lon: 0.0 },
    'southeast asia': { lat: 5.0, lon: 110.0 },
    'west coast': { lat: 37.77, lon: -122.42 },
    'east coast': { lat: 40.71, lon: -74.01 },
    'northern israel': { lat: 32.95, lon: 35.53 },
    'southern israel': { lat: 30.85, lon: 34.75 },
    'central israel': { lat: 31.95, lon: 34.90 },
    'northern gaza': { lat: 31.55, lon: 34.50 },
    'southern gaza': { lat: 31.30, lon: 34.30 },
};

export const CONTINENT_FALLBACKS: Record<string, { lat: number; lon: number }> = {
    'europe': { lat: 54.5, lon: 15.2 },
    'africa': { lat: 8.7, lon: 20.9 },
    'asia': { lat: 34.0, lon: 100.0 },
    'oceania': { lat: -25.0, lon: 135.0 },
    'north america': { lat: 40.0, lon: -100.0 },
    'south america': { lat: -15.0, lon: -60.0 },
};

export const CONTINENT_NAMES = new Set(Object.keys(CONTINENT_FALLBACKS));

export const DEMONYM_MAP: Record<string, string> = {
    'american': 'united states', 'chinese': 'china', 'russian': 'russia',
    'indian': 'india', 'japanese': 'japan', 'german': 'germany', 'deutschland': 'germany',
    'french': 'france', 'british': 'united kingdom', 'canadian': 'canada',
    'brazilian': 'brazil', 'australian': 'australia', 'mexican': 'mexico',
    'italian': 'italy', 'spanish': 'spain', 'korean': 'south korea',
    'iranian': 'iran', 'iraqi': 'iraq', 'syrian': 'syria',
    'turkish': 'turkey', 'israeli': 'israel', 'palestinian': 'palestine',
    'egyptian': 'egypt', 'saudi': 'saudi arabia', 'pakistani': 'pakistan',
    'afghan': 'afghanistan', 'nigerian': 'nigeria', 'kenyan': 'kenya',
    'ethiopian': 'ethiopia', 'sudanese': 'sudan', 'somali': 'somalia',
    'libyan': 'libya', 'yemeni': 'yemen', 'lebanese': 'lebanon',
    'jordanian': 'jordan', 'polish': 'poland', 'dutch': 'netherlands',
    'belgian': 'belgium', 'swedish': 'sweden', 'norwegian': 'norway',
    'danish': 'denmark', 'finnish': 'finland', 'greek': 'greece',
    'portuguese': 'portugal', 'swiss': 'switzerland', 'austrian': 'austria',
    'romanian': 'romania', 'hungarian': 'hungary', 'czech': 'czech republic',
    'indonesian': 'indonesia', 'filipino': 'philippines', 'vietnamese': 'vietnam',
    'thai': 'thailand', 'taiwanese': 'taiwan', 'malaysian': 'malaysia',
    'singaporean': 'singapore', 'argentinian': 'argentina', 'colombian': 'colombia',
    'chilean': 'chile', 'venezuelan': 'venezuela', 'peruvian': 'peru',
    'cuban': 'cuba', 'irish': 'ireland', 'scottish': 'scotland',
    'welsh': 'wales', 'moroccan': 'morocco', 'tunisian': 'tunisia',
    'algerian': 'algeria', 'ecuadorian': 'ecuador', 'bolivian': 'bolivia',
    'ukrainian': 'ukraine', 'georgian': 'georgia', 'armenian': 'armenia',
    'uruguayan': 'uruguay', 'paraguayan': 'paraguay', 'bahraini': 'bahrain',
    'qatari': 'qatar', 'kuwaiti': 'kuwait', 'omani': 'oman',
    'congolese': 'democratic republic of the congo', 'tanzanian': 'tanzania',
    'ugandan': 'uganda', 'rwandan': 'rwanda', 'cameroonian': 'cameroon',
    'senegalese': 'senegal', 'ghanaian': 'ghana', 'ivorian': 'ivory coast',
    'mozambican': 'mozambique', 'zimbabwean': 'zimbabwe', 'zambian': 'zambia',
    'namibian': 'namibia', 'botswanan': 'botswana', 'malawian': 'malawi',
    'nepalese': 'nepal', 'sri lankan': 'sri lanka', 'burmese': 'myanmar',
    'cambodian': 'cambodia', 'laotian': 'laos',
    'siberian': 'siberia', 'crimean': 'crimea', 'arctic': 'arctic',
    'antarctic': 'antarctica', 'caribbean': 'caribbean',
    'balkan': 'balkans', 'scandinavian': 'scandinavia',
    'bavarian': 'germany', 'catalan': 'spain', 'tibetan': 'china',
};

export const COUNTRY_ABBREV_MAP: Record<string, string> = {
    'u.s.': 'united states', 'u.s.a.': 'united states', 'u.s': 'united states',
    'us': 'united states', 'america': 'united states',
    'u.k.': 'united kingdom', 'u.k': 'united kingdom', 'uk': 'united kingdom',
    'u.a.e.': 'united arab emirates', 'uae': 'united arab emirates',
    'u.n.': '__skip__',
    'e.u.': '__skip__',
    'd.c.': 'washington dc',
};

export const DATELINE_NOISE_WORDS = new Set([
    'live', 'updates', 'update', 'breaking', 'latest', 'analysis',
    'opinion', 'editorial', 'exclusive', 'recap', 'roundup', 'review',
    'briefing', 'explainer', 'report', 'summary', 'watch', 'alert',
    'blog', 'tracker', 'results', 'polls', 'podcast', 'newsletter',
    'centcom', 'eucom', 'africom', 'indopacom', 'southcom', 'northcom',
    'brief', 'briefing', 'coverage', 'thread', 'timeline',
]);

export const STOP_WORDS = new Set([
    'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august',
    'september', 'october', 'november', 'december', 'monday', 'tuesday',
    'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
    'spring', 'summer', 'fall', 'winter',
    'the', 'this', 'that', 'these', 'those', 'what', 'which', 'who', 'how',
    'just', 'new', 'more', 'most', 'some', 'many', 'much', 'its', 'his', 'her',
    'their', 'our', 'all', 'one', 'two', 'three', 'four', 'five',
    'congress', 'senate', 'parliament', 'reuters', 'associated',
    'press', 'exclusive', 'breaking', 'update', 'live', 'latest',
    'report', 'reports', 'analysis', 'opinion', 'editorial',
    'trump', 'biden', 'putin', 'modi', 'macron', 'scholz', 'zelenskyy',
    'zelensky', 'netanyahu', 'xi', 'obama', 'pope', 'elon', 'musk',
    'democrats', 'republicans', 'nato', 'opec', 'who', 'fbi', 'cia',
    'deal', 'record', 'back', 'first', 'second', 'third', 'over',
    'after', 'before', 'major', 'global', 'world', 'international',
    'north', 'south', 'east', 'west', 'says', 'say', 'said',
    'each', 'every', 'both', 'other', 'another', 'such',
    'high', 'higher', 'low', 'lower', 'big', 'small', 'long',
    'war', 'peace', 'crisis', 'today', 'yesterday', 'tomorrow',
    'government', 'president', 'minister', 'prime', 'general',
    'military', 'army', 'force', 'forces', 'troops', 'police',
    'court', 'supreme', 'justice', 'law', 'bill', 'act',
    'company', 'companies', 'stocks', 'market', 'markets',
    'people', 'officials', 'sources', 'leaders', 'workers',
    'nasa', 'esa', 'spacex', 'jaxa', 'isro', 'roscosmos',
    'un', 'united nations', 'imf', 'interpol',
    'centcom', 'eucom', 'africom', 'indopacom', 'southcom', 'northcom',
    'socom', 'transcom', 'stratcom', 'cybercom', 'spacecom',
    'moon', 'sun', 'venus', 'mars', 'jupiter', 'saturn', 'mercury',
    'neptune', 'uranus', 'pluto', 'earth', 'lunar', 'solar',
    'asteroid', 'comet', 'nebula', 'galaxy', 'orbit', 'spacecraft',
    'island', 'islands', 'peninsula', 'continent', 'region', 'area',
    'coast', 'mountain', 'river', 'lake', 'ocean', 'sea', 'bay', 'gulf',
    'man', 'humble', 'bowen', 'country', 'source', 'category', 'theme', 'format', 'topic',
    'et', 'pt', 'ct', 'mt', 'est', 'pst', 'cst', 'mst', 'gmt', 'utc',
    'hong', 'kong', 'abu', 'san', 'los', 'las', 'das', 'del', 'der',
    'jos', 'america', 'intel', 'defence', 'intelligence',
]);

export const FALSE_POSITIVES = new Set([
    'paris hilton', 'jackson hole', 'georgia tech',
    'chelsea clinton', 'chelsea handler', 'virginia woolf',
    'arsenal', 'chelsea fc', 'manchester united', 'manchester city',
    'real madrid', 'bayern munich', 'juventus', 'napoli',
    'tottenham', 'everton', 'wolverhampton', 'newcastle united',
    'amazon', 'apple', 'oracle', 'adobe', 'cisco',
    'liveuamap', 'nitter', 'osint',
    'geoconfirmed', 'intelcrab', 'auroraintel', 'osinttechnical',
    'research roundup', 'audio long read', 'author correction',
    'weekend of war', 'morning edition', 'evening update',
    'daily briefing', 'weekly roundup', 'year in review',
    'gulf war', 'cold war', 'world war', 'civil war', 'arab spring',
    'iron dome', 'iron curtain', 'enterprise software', 'morning report',
    'evening report', 'special report', 'market update', 'daily dispatch',
    'breaking news', 'live coverage', 'press release', 'intelligence brief',
]);

export const NEWS_SOURCE_DEFAULTS: Record<string, string> = {
    'nasa': 'Washington DC',
    'nature': 'London',
    'ars technica': 'San Francisco',
    'the verge': 'New York',
    'who': 'Geneva',
};

export const SUPERPOWER_KEYS = new Set(['united states', 'united kingdom']);
